development:
  adapter: postgresql
  encoding: unicode
  database: drinkn_development
  pool: 5
  username: admin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: drinkn_test
  pool: 5
  username: admin
  password:
